<?php
$texts = [
    'it' => [
        // base_layout & page names
        'skip' => 'Salta al contenuto',
        'nav_toggle' => 'apri/chiudi barra navigazione',
        'breadcrumb' => 'Ti trovi in:',
        'lang_switch' => '<span lang="en">Go to the english version</span>',
        'index' => '<span lang="en">Home</span>',
        'user_area' => 'Area Utente',
        'login' => '<span lang="en">Login</span>',
        'signup' => 'Registra Account',
        'logout' => '<span lang="en">Logout</span>',
        'admin' => 'Amministrazione',
        'booking' => 'Prenota',
        'edit_booking' => 'Modifica Prenotazione',
        'create_review' => 'Crea Recensione',
        'edit_review' => 'Modifica Recensione',
        'room_administration' => 'Amministrazione Stanza',
        // Admin
        'rooms' => 'Stanze',
        // Room Administration
        // User Area
        'in_as' => 'Attualmente loggati come: ',
        'next_bookings' => 'Prossime Prenotazioni:',
        'past_bookings' => 'Prenotazioni Passate:',
        'write_reviews' => 'Scrivi una recensione:',
        'written_reviews' => 'Recensioni scritte:',
        'no_next_bookings' => 'Non hai prenotazioni future.',
        'no_past_bookings' => 'Non hai prenotazioni passate.',
        'no_available_review' => 'Non hai stanze da recensire',
        'no_written_review' => 'Non hai recensioni scritte.',
        'room' => 'Stanza',
        'edit' => 'Modifica',
        'create_review_for' => 'Crea recensione per Stanza',
        'score' => 'Valutazione',
        'text' => 'Testo',
        'edit_a_review' => 'Modifica recensione',
        'date' => 'Data',
        'time' => 'Orario',
        // Create Review
        'create_review_for_num' => 'Crea Recensione per stanza: ',
        'write_review' => 'Scrivi la recensione',
        'create_review_button' => 'Crea',
        // Index
        'difficulty' => 'Difficoltà',
        'players' => 'Giocatori',
        'duration' => 'Durata',
        'booking_button' => 'Prenota Ora',
        'diff_easy' => 'Facile',
        'diff_medium' => 'Media',
        'diff_hard' => 'Difficile',
        // Login
        'register_prompt' => 'Non hai un <span lang="en">account</span>?',
        'register_link' => 'Registrati adesso',
        'label_username' => '<span lang="en">Username</span>',
        'label_password' => '<span lang="en">Password</span>',
        'login_button' => 'Accedi',
        // Logout
        'logout_success' => 'Logout effettuato con successo.',
        'login_link' => 'Clicca qui per effettuare il login',
        // Edit Booking
        'edit_booking_ID' => 'Modifica prenotazione ID',
        'the_booking' => 'Prenotazione',
        'delete' => 'Elimina',
        'new_day_select' => 'Selezione del nuovo giorno',
        'new_slot_select' => 'Selezione del nuovo slot orario',
        // Edit Review
        'edit_the_review' => 'Modifica la recensione',
        // Booking
        'room_booking' => 'Prenotazione Stanza',
        'book' => 'Prenota',
        'day_select' => 'Selezione del giorno',
        'slot_select' => 'Selezione dello slot orario',
        // Signup
        'prompt_login' => 'Hai gia un account?',
        'login_button_alt' => 'accedi qui',
        'legend_anagrafica' => 'Anagrafica',
        'name_label' => 'Nome',
        'surname_label' => 'Cognome',
        'birth_label' => 'Data di nascita',
        'contacts_legend' => 'Contatti',
        'phone_label' => 'Telefono',
        'email_label' => '<span lang="en">Email</span>',
        'account_legend' => 'Info <span lang="en">Login</span>',
        'confirm_label' => 'Conferma <span lang="en">Password</span>',
        'signup_button' => "Registra",
        // Errors
        'connection_error' => 'Errore di Connessione.',
        'nonexistent_user' => 'Questo utente non esiste.',
        'incorrect_password' => 'La <span lang="en">password</span> è errata.',
        'username_not_valid' => 'Il nome utente non è valido.',
        'password_not_valid' => 'La <span lang="en">password</span> non è valida.',
        'email_not_valid' => 'La <span lang="en">email</span> non è valida.',
        'phone_number_not_valid' => 'Il numero di telefono non è valido.',
        'review_not_valid' => 'La recensione non è valida.',
        'name_not_valid' => 'Nome e Cognome devono contenere solo lettere.',
        'username_already_present' => 'Questo nome utente è già in uso.',
        'signup_error' => "C'è stato un problema durante la registrazione.",
        'passwords_not_the_same' => 'Le due password devono essere uguali.',
        'signup_name_error' => 'Il nome non può contenere numeri e non può essere vuoto.',
        'signup_surname_error' => 'Il cognome non può contenere numeri e non può essere vuoto.',
        'signup_phone_number_error' => 'Il numero di telefono non è valido.',
        'signup_email_error' => "L'<span>email</span> non è valida.",
        'signup_username_error' => 'Il nome utente non è valido.',
        'signup_password_error' => 'La <span lang="en">password</span> deve contenere: minimo 8 caratteri, 1 lettera maiuscola, 1 lettera minuscola e 1 carattere speciale.',
        'signup_confirmation_password_error' => 'Le <span>password</span> non coincidono.',
        // Info
        'room_booked' => 'La stanza è stata prenotata.',
        'needed_login' => 'Devi prima aver fatto il <span lang="en">login</span>.',
        // Titles
        'User_Area' => 'Area Utente',
        'Admin' => 'Amministrazione',
        'Login' => 'Accedi',
        'Signup' => 'Registrazione',
        'Logout' => 'Logout',
        'Booking' => 'Prenotazione',
        'Edit_Booking' => 'Modifica Prenotazione',
        'Create_Review' => 'Creazione Recensione',
        'Edit_Review' => 'Modifica Recensione',
        'Room_Administration' => 'Amministrazione Stanza',
        // Descriptions
        'Admin_Description' => 'Pagina di amministrazione di En?gma. Scegli una stanza da amministrare.',
        'Booking_Description' => 'Prenota una stanza. Puoi scegliere una data e lo slot orario.',
        'Create_Review_Description' => 'Crea una recensione per una stanza che hai vissuto.',
        'Edit_Booking_Description' => 'Modifica una futura prenotazione. Puoi scegliere un nuovo giorno o un nuovo slot orario.',
        'Edit_Review_Description' => 'Modifica una recensione precedentemente scritta.',
        'Index_Description' => 'Visualizza e prenota le escape room di En?gma',
        'Login_Description' => 'Accedi al tuo account.',
        'Logout_Description' => 'Scollegati dal tuo account.',
        'Room_Administration_Description' => 'Visualizza le prossime prenotazioni fatte dai clienti di questa specifica stanza.',
        'Signup_Description' => 'Registrati al sito.',
        'User_Area_Description' => 'Visualizza le prossime e passate prenotazioni. Inoltre è possibile creare recensioni e modificare quelle precedentemente scritte.',
        // Keywords
        'Admin_Keywords' => '',
        'Booking_Keywords' => '',
        'Create_Review_Keywords' => '',
        'Edit_Booking_Keywords' => '',
        'Edit_Review_Keywords' => '',
        'Index_Keywords' => 'Escape rooms, Cripta Arcana, Sabotaggio sul treno, Riavvio del Reattore',
        'Login_Keywords' => '',
        'Logout_Keywords' => '',
        'Room_Administration_Keywords' => '',
        'Signup_Keywords' => '',
        'User_Area_Keywords' => ''
    ],
    'en' => [
        // base_layout & page names
        'skip' => 'Skip to content',
        'nav_toggle' => 'open/close navigation bar',
        'breadcrumb' => 'You are in:',
        'lang_switch' => '<span lang="it">Vai alla versione italiana</span>',
        'index' => 'Home',
        'user_area' => 'User Area',
        'login' => 'Login',
        'signup' => 'Sign Up',
        'logout' => 'Logout',
        'admin' => 'Administration',
        'booking' => 'Room Booking',
        'edit_booking' => 'Edit Booking',
        'create_review' => 'Create Review',
        'edit_review' => 'Edit Review',
        'room_administration' => 'Room Administration',
        // Admin
        'rooms' => 'Rooms',
        // Room Administration
        // User Area
        'in_as' => 'Currently logged in as: ',
        'next_bookings' => 'Next Bookings:',
        'past_bookings' => 'Past Bookings:',
        'write_reviews' => 'Write a review:',
        'written_reviews' => 'Written Reviews:',
        'no_next_bookings' => "You don't have any next booking.",
        'no_past_bookings' => "You don't have any past booking.",
        'no_available_review' => "You don't have any room to review.",
        'no_written_review' => "You don't have any review.",
        'room' => 'Room',
        'edit' => 'Edit',
        'create_review_for' => 'Create a review for Room',
        'score' => 'Score',
        'text' => 'Text',
        'edit_a_review' => 'Edit review',
        'date' => 'Date',
        'time' => 'Time',
        // Create Review
        'create_review_for_num' => 'Write review for room: ',
        'write_review' => 'Write the review',
        'create_review_button' => 'Create',
        // Index
        'difficulty' => 'Difficulty',
        'players' => 'Players',
        'duration' => 'Duration',
        'booking_button' => 'Book Now',
        'diff_easy' => 'Easy',
        'diff_medium' => 'Medium',
        'diff_hard' => 'Hard',
        // Login
        'register_prompt' => "Don't have an account?",
        'register_link' => 'Register now',
        'label_username' => 'Username',
        'label_password' => 'Password',
        'login_button' => 'Login',
        // Logout
        'logout_success' => 'Logged out successfully.',
        'login_link' => 'Click here to login',
        // Edit Booking
        'edit_booking_ID' => 'Edit booking ID',
        'the_booking' => 'Booking',
        'delete' => 'Delete',
        'new_day_select' => 'Select new day',
        'new_slot_select' => 'Select new time slot',
        // Edit Review
        'edit_the_review' => 'Edit the review',
        // Booking
        'room_booking' => 'Room Booking',
        'book' => 'Book',
        'day_select' => 'Select day',
        'slot_select' => 'Select time slot',
        // Signup
        'prompt_login' => 'Already have an account?',
        'login_button_alt' => 'Login here',
        'legend_anagrafica' => 'Registry Info',
        'name_label' => 'First name',
        'surname_label' => 'Last name',
        'birth_label' => 'Date of birth',
        'contacts_legend' => 'Contacts',
        'phone_label' => 'Phone Number',
        'email_label' => 'Email',
        'account_legend' => 'Login Info',
        'confirm_label' => 'Confirm Password',
        'signup_button' => 'Sign Up',
        // Errors
        'connection_error' => 'Connection Error.',
        'nonexistent_user' => "This user doesn't exists.",
        'incorrect_password' => 'Incorrect Password.',
        'username_not_valid' => 'The username is not valid.',
        'password_not_valid' => 'The password is not valid',
        'email_not_valid' => 'The email is not valid.',
        'phone_number_not_valid' => 'The phone number is not valid.',
        'review_not_valid' => 'The review is not valid.',
        'name_not_valid' => 'Name and Surname have to contain only letters.',
        'username_already_present' => 'The username is already in use.',
        'signup_error' => 'There was a problem during the sign up.',
        'passwords_not_the_same' => 'The passwords must be the same.',
        'signup_name_error' => 'The name cannot contain numbers and be empty.',
        'signup_surname_error' => 'The surname cannot contain numbers and be empty.',
        'signup_phone_number_error' => 'The phone number is not valid.',
        'signup_email_error' => 'The email is not valid.',
        'signup_username_error' => 'The username is not valid.',
        'signup_password_error' => 'The password must contain: minimum 8 characters, 1 uppercase letter, 1 lowercase letter and 1 special character.',
        'signup_confirmation_password_error' => 'The passwords are not the same.',
        // Info
        'room_booked' => 'The room has been booked.',
        'needed_login' => 'You first need to login.',
        // Titles
        'User_Area' => 'User Area',
        'Admin' => 'Administration',
        'Login' => 'Login',
        'Signup' => 'Signup',
        'Logout' => 'Logout',
        'Booking' => 'Room Booking',
        'Edit_Booking' => 'Edit Booking',
        'Create_Review' => 'Create Review',
        'Edit_Review' => 'Edit Review',
        'Room_Administration' => 'Room Administration',
        // Descriptions
        'Admin_Description' => 'Administration page of En?gma. Choose a room to administer.',
        'Booking_Description' => 'Book an escape room. You can choose the day and the time slot.',
        'Create_Review_Description' => 'Create a review for a room that you experienced.',
        'Edit_Booking_Description' => 'Modify a future booking to better suit your needs. You can choose a new date or a new time slot.',
        'Edit_Review_Description' => 'Edit a review that was written in the past if you feel like somehow your idea was changed.',
        'Index_Description' => "Explore and book En?gma's escape rooms.",
        'Login_Description' => 'Log into your account.',
        'Logout_Description' => 'Log out from your account.',
        'Room_Administration_Description' => 'Check what are the next booking made by the clients for this particular room.',
        'Signup_Description' => 'Sign up for a new account in the website.',
        'User_Area_Description' => 'Check the records of your next and past bookings. You can also create new reviews and edit past reviews.',
        // Keywords
        'Admin_Keywords' => '',
        'Booking_Keywords' => '',
        'Create_Review_Keywords' => '',
        'Edit_Booking_Keywords' => '',
        'Edit_Review_Keywords' => '',
        'Index_Keywords' => 'Escape rooms, Magic Dungeon, Train Sabotage, Reactor Reboot',
        'Login_Keywords' => '',
        'Logout_Keywords' => '',
        'Room_Administration_Keywords' => '',
        'Signup_Keywords' => '',
        'User_Area_Keywords' => ''
    ]
];