<?php
$texts = [
    'it' => [
        // base_layout & page names
        'skip' => 'Salta al contenuto',
        'nav_toggle' => 'apri/chiudi barra navigazione',
        'breadcrumb' => 'Ti trovi in:',
        'lang_switch' => 'Vai alla versione inglese',
        'index' => '<span lang=en>Home</span>',
        'user_area' => 'Area Utente',
        'login' => '<span lang=en>Login</span>',
        'signup' => 'Registra Account',
        'logout' => '<span lang=en>Logout</span>',
        'admin' => 'Amministrazione',
        'booking' => 'Prenota',
        'edit_booking' => 'Modifica Prenotazione',
        'create_review' => 'Crea Recensione',
        'edit_review' => 'Modifica Recensione',
        'room_administration' => 'Amministrazione Stanza',
        // Admin
        'rooms' => 'Stanze',
        // Room Administration
        // User Area
        'in_as' => 'Attualmente loggati come: ',
        'next_bookings' => 'Prossime Prenotazioni:',
        'past_bookings' => 'Prenotazioni Passate:',
        'write_reviews' => 'Scrivi una recensione:',
        'written_reviews' => 'Recensioni scritte:',
        'no_next_bookings' => 'Non hai prenotazioni future.',
        'no_past_bookings' => 'Non hai prenotazioni passate.',
        'no_available_review' => 'Non hai stanze da recensire',
        'no_written_review' => 'Non hai recensioni scritte.',
        'room' => 'Stanza',
        'edit' => 'Modifica',
        'create_review_for' => 'Crea recensione per Stanza',
        'score' => 'Valutazione',
        'text' => 'Testo',
        'edit_a_review' => 'Modifica recensione',
        // Create Review
        'create_review_for_num' => 'Crea Recensione per stanza n',
        'write_review' => 'Scrivi la recensione',
        'create_review_button' => 'Crea',
        // Index
        'difficulty' => 'Difficoltà',
        'players' => 'Giocatori',
        'time' => 'Durata',
        'booking_button' => 'Prenota Ora',
        // Login
        'register_prompt' => 'Non hai un <span lang="en">account</span>?',
        'register_link' => 'Registrati adesso',
        'label_username' => '<span lang="en">Username</span>',
        'label_password' => '<span lang="en">Password</span>',
        'login_button' => 'Accedi',
        // Logout
        'logout_success' => 'Logout effettuato con successo',
        'login_link' => 'Clicca qui per effettuare il login',
        // Edit Booking
        'edit_booking_ID' => 'Modifica prenotazione ID',
        'the_booking' => 'Prenotazione',
        'by' => 'da',
        'where' => 'alla stanza',
        'delete' => 'Elimina',
        'day_select' => 'Selezione del giorno',
        'slot_select' => 'Selezione dello slot',
        // Edit Review
        'edit_the_review' => 'Modifica la recensione',
        // Booking
        'room_booking' => 'Prenotazione Stanza',
        'book' => 'Prenota',
        // Signup
        'prompt_login' => 'Hai gia un account?',
        'login_button_alt' => 'accedi qui',
        'legend_anagrafica' => 'Anagrafica',
        'name_label' => 'Nome',
        'surname_label' => 'Cognome',
        'birth_label' => 'Data di nascita',
        'contacts_legend' => 'Contatti',
        'phone_label' => 'Telefono',
        'email_label' => '<span lang="en">Email</span>',
        'account_legend' => 'Info <span lang="en">Login</span>',
        'confirm_label' => 'Conferma <span lang="en">Password</span>',
        'signup_button' => "Registra",
        // Errors
        'connection_error' => 'Errore di Connessione.',
        'nonexistent_user' => 'Questo utente non esiste.',
        'incorrect_password' => 'La <span lang="en">password</span> è errata.',
        'username_not_valid' => 'Il nome utente non è valido.',
        'password_not_valid' => 'La <span lang="en">password</span> non è valida.',
        'email_not_valid' => 'La <span lang="en">email</span> non è valida.',
        'phone_number_not_valid' => 'Il numero di telefono non è valido.',
        'review_not_valid' => 'La recensione non è valida.',
        'name_not_valid' => 'Nome e Cognome devono contenere solo lettere.',
        'username_already_present' => 'Questo nome utente è già in uso.',
        'signup_error' => "C'è stato un problema durante la registrazione.",
        'passwords_not_the_same' => 'Le due passwords devono essere uguali.',
        // Info
        'room_booked' => 'La stanza è stata prenotata.',
        'needed_login' => 'Devi prima aver fatto il <span lang="en">login</span>.',
        // Titles
        'User_Area' => 'Area Utente',
        'Admin' => 'Amministrazione',
        'Login' => 'Accedi',
        'Signup' => 'Registrazione',
        'Logout' => 'Logout',
        'Booking' => 'Prenotazione',
        'Edit_Booking' => 'Modifica Prenotazione',
        'Create_Review' => 'Creazione Recensione',
        'Edit_Review' => 'Modifica Recensione',
        'Room_Administration' => 'Amministrazione Stanza',
        // Footer
        'contacts_title' => 'Contatti',
        'phone_label' => 'Telefono',
        'phone_number' => '123-456-7890',
        'email_label' => 'Email',
        'email_address' => 'enigma@gmail.com',
        'find_us_title' => 'Dove trovarci',
        'address' => 'Via dalì 13, 01210 Padova PD, Italia',
        'follow_us_title' => 'Seguici su',
        'instagram_link' => 'https://www.instagram.com',
        'facebook_link' => 'https://www.facebook.com',
    ],
    'en' => [
        // base_layout & page names
        'skip' => 'Skip to content',
        'nav_toggle' => 'open/close navigation bar',
        'breadcrumb' => 'You are in:',
        'lang_switch' => 'Go to Italian version',
        'index' => 'Home',
        'user_area' => 'User Area',
        'login' => 'Login',
        'signup' => 'Sign Up',
        'logout' => 'Logout',
        'admin' => 'Administration',
        'booking' => 'Book',
        'edit_booking' => 'Edit Booking',
        'create_review' => 'Create Review',
        'edit_review' => 'Edit Review',
        'room_administration' => 'Room Administration',
        // Admin
        'rooms' => 'Rooms',
        // Room Administration
        // User Area
        'in_as' => 'Currently logged in as: ',
        'next_bookings' => 'Next Bookings:',
        'past_bookings' => 'Past Bookings:',
        'write_reviews' => 'Write a review:',
        'written_reviews' => 'Written Reviews:',
        'no_next_bookings' => "You don't have any next booking.",
        'no_past_bookings' => "You don't have any past booking.",
        'no_available_review' => "You don't have any room to review.",
        'no_written_review' => "You don't have any review.",
        'room' => 'Room',
        'edit' => 'Edit',
        'create_review_for' => 'Create a review for Room',
        'score' => 'Score',
        'text' => 'Text',
        'edit_a_review' => 'Edit review',
        // Create Review
        'create_review_for_num' => 'Write review for room n',
        'write_review' => 'Write the review',
        'create_review_button' => 'Create',
        // Index
        'difficulty' => 'Difficulty',
        'players' => 'Players',
        'time' => 'Duration',
        'booking_button' => 'Book Now',
        // Login
        'register_prompt' => "Don't have an account?",
        'register_link' => 'Register now',
        'label_username' => 'Username',
        'label_password' => 'Password',
        'login_button' => 'Login',
        // Logout
        'logout_success' => 'Logged out successfully',
        'login_link' => 'Click here to login',
        // Edit Booking
        'edit_booking_ID' => 'Edit booking ID',
        'the_booking' => 'Booking',
        'by' => 'by',
        'where' => 'at Room',
        'delete' => 'Delete',
        'day_select' => 'Select day',
        'slot_select' => 'Select slot',
        // Edit Review
        'edit_the_review' => 'Edit the review',
        // Booking
        'room_booking' => 'Room Booking',
        'book' => 'Book',
        // Signup
        'prompt_login' => 'Already have an account?',
        'login_button_alt' => 'Login here',
        'legend_anagrafica' => 'Registry Info',
        'name_label' => 'First name',
        'surname_label' => 'Last name',
        'birth_label' => 'Date of birth',
        'contacts_legend' => 'Contacts',
        'phone_label' => 'Phone Number',
        'email_label' => 'Email',
        'account_legend' => 'Login Info',
        'confirm_label' => 'Confirm Password',
        'signup_button' => 'Sign Up',
        // Errors
        'connection_error' => 'Connection Error.',
        'nonexistent_user' => "This user doesn't exists.",
        'incorrect_password' => 'Incorrect Password.',
        'username_not_valid' => 'The username is not valid.',
        'password_not_valid' => 'The password is not valid',
        'email_not_valid' => 'The email is not valid.',
        'phone_number_not_valid' => 'The phone number is not valid.',
        'review_not_valid' => 'The review is not valid.',
        'name_not_valid' => 'Name and Surname have to contain only letters.',
        'username_already_present' => 'The username is already in use.',
        'signup_error' => 'There was a problem during the sign up.',
        'passwords_not_the_same' => 'The passwords must be the same.',
        // Info
        'room_booked' => 'The room has been booked.',
        'needed_login' => 'You first need to login.',
        // Titles
        'User_Area' => 'User Area',
        'Admin' => 'Administration',
        'Login' => 'Login',
        'Signup' => 'Signup',
        'Logout' => 'Logout',
        'Booking' => 'Room Booking',
        'Edit_Booking' => 'Edit Booking',
        'Create_Review' => 'Create Review',
        'Edit_Review' => 'Edit Review',
        'Room_Administration' => 'Room Administration',
        // Footer
        'contacts_title' => 'Contacts',
        'phone_label' => 'Phone',
        'phone_number' => '123-456-7890',
        'email_label' => 'Email',
        'email_address' => 'info@example.com',
        'find_us_title' => 'Where to find us',
        'address' => '13 dalì, Padova, Italy',
        'follow_us_title' => 'Follow us on',
        'instagram_link' => 'https://www.instagram.com',
        'facebook_link' => 'https://www.facebook.com',
    ]
];