navbar=false;
document.onload=function(){
    document.getElementById("navtoggle").onclick=function(){
        if(navbar){
            document.getElementById("navmenu").classList.add("closednav");
        }
        else{
            document.getElementById("navmenu").classList.remove("closednav");
        }
        navbar=!navbar;
    }
}